nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['http://localhost:8080/']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
            max_age: 3600
